import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren): JSX.Element => (
  <html lang="en">
    <head>
      <link
        href="https://fonts.googleapis.com/css2?family=Caprasimo&display=swap"
        rel="stylesheet"
      />
    </head>
    <body className={inter.className}>{children}</body>
  </html>
);

export default RootLayout;
